use crate::ast::*;

pub fn transpile(song: &Song) -> String {
    let mut out = String::new();
    let beat_dur = 60.0 / song.tempo as f32;

    out.push_str("// Generated by Sonara\n\n");

    out.push_str(&synth_defs());

    out.push_str("(\n");
    out.push_str(&format!("var beatDur = {}; // secs/quarter-note @ {} bpm\n\n", beat_dur, song.tempo));

    // Compute section offsets in seconds
    let mut offset = 0.0f32;
    for section in &song.sections {
        let dur = section_duration(section, beat_dur);
        out.push_str(&format!("// ── section: {} (offset {:.2}s) ──\n", section.name, offset));
        out.push_str(&section_routines(section, offset, beat_dur));
        out.push('\n');
        offset += dur;
    }

    out.push_str(")\n");
    out
}

fn synth_defs() -> String {
    "// ── Synth Definitions ─────────────────────────────────────────────────
// Evaluate this block first (select all and run), or run in a separate block
// before playing the song.

SynthDef(\\sonaraChord, { |out=0, freq=440, amp=0.12, dur=2.0|
    var sig = Mix.ar(Saw.ar(freq * [1, 2, 3], amp / 3));
    var env = EnvGen.kr(Env.linen(0.02, dur - 0.1, 0.08), doneAction: 2);
    Out.ar(out, (sig * env).dup);
}).add;

SynthDef(\\sonaraMelody, { |out=0, freq=440, amp=0.4, dur=0.5|
    var sig = SinOsc.ar(freq, 0, amp) + Pulse.ar(freq, 0.3, amp * 0.2);
    var env = EnvGen.kr(Env.perc(0.01, dur * 0.85), doneAction: 2);
    Out.ar(out, (sig * env).dup);
}).add;

SynthDef(\\sonaraBass, { |out=0, freq=110, amp=0.35, dur=1.0|
    var sig = SinOsc.ar(freq, 0, amp) + SinOsc.ar(freq * 2, 0, amp * 0.3);
    var env = EnvGen.kr(Env.perc(0.01, dur * 0.9), doneAction: 2);
    Out.ar(out, (sig * env).dup);
}).add;

SynthDef(\\sonaraKick, { |out=0, amp=0.8|
    var freq = EnvGen.kr(Env([200, 60, 40], [0.01, 0.1]));
    var sig  = SinOsc.ar(freq, 0, amp);
    var env  = EnvGen.kr(Env.perc(0.005, 0.3), doneAction: 2);
    Out.ar(out, (sig * env).dup);
}).add;

SynthDef(\\sonaraSnare, { |out=0, amp=0.6|
    var sig = WhiteNoise.ar(amp) * 0.7 + SinOsc.ar(180, 0, amp * 0.3);
    var env = EnvGen.kr(Env.perc(0.005, 0.15), doneAction: 2);
    Out.ar(out, (sig * env).dup);
}).add;

SynthDef(\\sonaraHihat, { |out=0, amp=0.3|
    var sig = HPF.ar(WhiteNoise.ar(amp), 8000);
    var env = EnvGen.kr(Env.perc(0.001, 0.06), doneAction: 2);
    Out.ar(out, (sig * env).dup);
}).add;

s.sync; // wait for defs to register before playing

".to_string()
}

fn section_routines(section: &Section, offset: f32, beat_dur: f32) -> String {
    let mut out = String::new();

    if !section.chords.is_empty() {
        out.push_str(&format!("// chords: {}\n", section.name));
        out.push_str("Routine({\n");
        out.push_str(&format!("    {:.3}.wait;\n", offset));
        for chord in &section.chords {
            let chord_dur = beat_dur * 4.0;
            for midi in chord.to_midi_notes() {
                let freq = midi_to_freq(midi);
                out.push_str(&format!(
                    "    Synth(\\sonaraChord, [\\freq, {:.2}, \\amp, 0.12, \\dur, {:.3}]);\n",
                    freq, chord_dur
                ));
            }
            out.push_str(&format!("    {:.3}.wait;\n", chord_dur));
        }
        out.push_str("}).play;\n\n");
    }

    if !section.bass.is_empty() {
        out.push_str(&format!("// bass: {}\n", section.name));
        out.push_str("Routine({\n");
        out.push_str(&format!("    {:.3}.wait;\n", offset));
        for note in &section.bass {
            let dur = beat_dur * note.duration.beats();
            let freq = midi_to_freq(note.to_midi());
            out.push_str(&format!(
                "    Synth(\\sonaraBass, [\\freq, {:.2}, \\amp, 0.35, \\dur, {:.3}]);\n",
                freq, dur
            ));
            out.push_str(&format!("    {:.3}.wait;\n", dur));
        }
        out.push_str("}).play;\n\n");
    }

    if !section.melody.is_empty() {
        out.push_str(&format!("// melody: {}\n", section.name));
        out.push_str("Routine({\n");
        out.push_str(&format!("    {:.3}.wait;\n", offset));
        for note in &section.melody {
            let dur = beat_dur * note.duration.beats();
            let freq = midi_to_freq(note.to_midi());
            out.push_str(&format!(
                "    Synth(\\sonaraMelody, [\\freq, {:.2}, \\amp, 0.4, \\dur, {:.3}]);\n",
                freq, dur
            ));
            out.push_str(&format!("    {:.3}.wait;\n", dur));
        }
        out.push_str("}).play;\n\n");
    }

    if !section.drums.is_empty() {
        out.push_str(&format!("// drums: {}\n", section.name));
        out.push_str("Routine({\n");
        out.push_str(&format!("    {:.3}.wait;\n", offset));
        for hit in &section.drums {
            match hit {
                DrumHit::Kick  => out.push_str("    Synth(\\sonaraKick);\n"),
                DrumHit::Snare => out.push_str("    Synth(\\sonaraSnare);\n"),
                DrumHit::HiHat => out.push_str("    Synth(\\sonaraHihat);\n"),
                DrumHit::Rest  => {}
            }
            out.push_str(&format!("    {:.3}.wait;\n", beat_dur));
        }
        out.push_str("}).play;\n\n");
    }

    out
}

fn section_duration(section: &Section, beat_dur: f32) -> f32 {
    let chord_dur = section.chords.len() as f32 * beat_dur * 4.0;
    let melody_dur: f32 = section.melody.iter().map(|n| beat_dur * n.duration.beats()).sum();
    let bass_dur: f32 = section.bass.iter().map(|n| beat_dur * n.duration.beats()).sum();
    let drum_dur = section.drums.len() as f32 * beat_dur;
    chord_dur.max(melody_dur).max(bass_dur).max(drum_dur)
}

fn midi_to_freq(midi: u8) -> f32 {
    440.0 * 2.0_f32.powf((midi as f32 - 69.0) / 12.0)
}
